# Reload config
unbind r
bind r source-file ~/.tmux.conf

# General settings
set -g prefix C-s                # Leader Keybind Ctrl + S
set -g set-clipboard on          # Use system clipboard
set -g mouse on                  # Enable mouse for pane resizing
set -g base-index 1              # Start window indexing at 1
set -g pane-base-index 1         # Start pane indexing at 1
set -g renumber-windows on       # Renumber windows after closing one
set-option -g status-position top
set-option -g default-terminal 'tmux-256color'

# Vim-like pane navigation
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# TPM plugins
set -g @plugin 'plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'nordtheme/tmux'
set -g @plugin 'tmux-plugins/tmux-sensible'

# TPM initialization (keep at bottom)
run '~/.tmux/plugins/tpm/tpm'
