# Reload config
unbind r
bind r source-file ~/.tmux.conf

# General settings
set -g prefix C-s                # Leader Keybind Ctrl + S
set -g set-clipboard on          # Use system clipboard
set -g mouse on                  # Enable mouse for pane resizing
set -g base-index 1              # Start window indexing at 1
set -g pane-base-index 1         # Start pane indexing at 1
set -g renumber-windows on       # Renumber windows after closing one
set-option -g status-position top
set-option -g default-terminal 'tmux-256color'
# set-option -g terminal-overrides ',xterm-256color:RGB'

# Vim-like pane navigation
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# TPM plugins
set -g @plugin 'plugins/tpm'
set -g @plugin 'plugin/catppuccin'

# Catppuccin theme settings
set -g @catppuccin_flavor 'mocha' # latte, frappe, macchiato or mocha
set -g @catppuccin_status_left_separator ""
set -g @catppuccin_window_middle_separator ""
set -g @catppuccin_status_right_separator ""
set -g @catppuccin_status_connect_separator "no"
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_window_status_style "custom"
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#W#{?window_zoomed_flag,(),}"

# Status line
set -gF status-left "#{@catppuccin_status_session}"
set -gF status-right "#{E:@catppuccin_status_directory}#{E:@catppuccin_status_date_time}"

# TPM initialization (keep at bottom)
run '~/.tmux/plugins/tpm/tpm'

