# Set terminal colors
set -g default-terminal "tmux-256color"

# Reload config with prefix r
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# General settings
set -g prefix C-s                    # Leader Keybind Ctrl + S
set-option -g status-position top
set -g set-clipboard on              # Use system clipboard
set -g mouse on                      # Enable mouse for pane resizing
set -g base-index 1                  # Start window indexing at 1
set -g pane-base-index 1             # Start pane indexing at 1
set -g renumber-windows on           # Renumber windows after closing one

# Vim-like pane navigation
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# TPM plugins
set -g @plugin 'plugins/tpm'
set -g @plugin 'catppuccin/tmux'

# Catppuccin theme settings
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "basic"
set -g @catppuccin_status_background "default"
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_menu_selected_style "fg=#{@thm_surface_0},bg=#{@thm_yellow}"

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_session}"

# TPM initialization (keep at bottom)
run '~/.config/tmux/plugins/tpm/tpm'

