# Zsh configuration file for Linux

# Default Editor Env
export EDITOR='vim'

# Path to your oh-my-zsh config
export ZSH="$HOME/.oh-my-zsh"

# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="eastwood"
plugins=(git zsh-autosuggestions zsh-syntax-highlighting)
source $ZSH/oh-my-zsh.sh

# GPG
export GPG_TTY=$(tty)

# Custom Aliases
alias e="$EDITOR"
alias ls='ls -h'
alias la='la -lah'
alias bat='batcat'

# git aliases
alias gc='git clone'
alias gs='git status'
alias ga='git add'
alias gu='git pull'
alias gcm='git commit -m'
alias gp='git push'

# fzf opens the selected file in nvim
alias fnv='vim $(fzf -m --preview="batcat --color=always {}")'
